version: 2

shared: &shared
  working_directory: ~/repo
  docker:
    - image: docker:18.09.2
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build image
        command: |
          docker build -f test/Dockerfile --build-arg RUBY_VERSION -t franckverrot/clamav-client .
    - run:
        name: run tests
        command: |
          docker run franckverrot/clamav-client rake

jobs:
  "2.4":
    <<: *shared
    environment:
      RUBY_VERSION=2.4-stretch
  "2.5":
    <<: *shared
    environment:
      RUBY_VERSION=2.5-stretch
  "2.6":
    <<: *shared
    environment:
      RUBY_VERSION=2.6-stretch
  "2.7":
    <<: *shared
    environment:
      RUBY_VERSION=2.7-slim
  "tcp-socket":
    working_directory: ~/repo
    environment:
      - CLAMD_TCP_HOST: 127.0.0.1
      - CLAMD_TCP_PORT: 3310
    docker:
      - image: circleci/2.4
      - image: mailu/clamav:1.7
      steps:
        - checkout
        - restore_cache:
            keys:
              - bundler-{{ checksum "Gemfile.lock" }}
        - run: bundle install --path=vendor/bundle
        - run: mkdir -p tmp/; mkdir -p tmp/cache/
        - save_cache:
            key: bundler-{{ checksum "Gemfile.lock" }}
            paths:
              - ~/repo/vendor/bundle
        - run: ./spec/wait-for-it.sh localhost:3310 -t 120
        - run: bundle exec rake

workflows:
  version: 2
  build:
    jobs:
      - "2.4"
      - "2.5"
      - "2.6"
      - "2.7"
      - "tcp-socket"
